const riskScoreEl = document.getElementById("riskScore");
const threatTypeEl = document.getElementById("threatType");
const aiStatusEl = document.getElementById("aiStatus");
const explanationEl = document.getElementById("explanation");
const reasonsEl = document.getElementById("reasons");
const analyzeBtn = document.getElementById("analyzeBtn");
const downloadAlertEl = document.getElementById("downloadAlert");
const downloadTextEl = document.getElementById("downloadText");
const protectionCardEl = document.getElementById("protectionCard");
const protectionTextEl = document.getElementById("protectionText");

function queryActiveTab() {
    return new Promise((resolve) => {
        chrome.tabs.query({ active: true, currentWindow: true }, (tabs) =>
            resolve(tabs[0] || null),
        );
    });
}

function runtimeMessage(payload) {
    return new Promise((resolve) => {
        chrome.runtime.sendMessage(payload, (response) => {
            if (chrome.runtime.lastError) {
                resolve(null);
                return;
            }
            resolve(response || null);
        });
    });
}

function getScoreColor(score) {
    if (score >= 70) return "#fb7185";
    if (score >= 45) return "#f59e0b";
    return "#34d399";
}

function renderReasons(reasons) {
    reasonsEl.innerHTML = "";
    (reasons || []).slice(0, 3).forEach((reason) => {
        const li = document.createElement("li");
        li.textContent = reason;
        reasonsEl.appendChild(li);
    });
}

function renderDownloadAlert(alert) {
    if (!alert) {
        downloadAlertEl.classList.add("hidden");
        return;
    }

    downloadAlertEl.classList.remove("hidden");
    downloadTextEl.textContent = `${alert.filename || "A file"} scored ${alert.risk_score}/100. ${alert.reasons.join(" ")}`;
}

function renderProtectionEvent(event) {
    if (!event) {
        protectionCardEl.classList.add("hidden");
        return;
    }

    protectionCardEl.classList.remove("hidden");
    const scoreText =
        typeof event.risk_score === "number"
            ? `${event.risk_score}/100`
            : "unknown";
    protectionTextEl.textContent = `I blocked a ${event.threat_type || "risky action"} (risk ${scoreText}) to keep you safe. ${event.explanation || ""}`;
}

function renderReport(report) {
    if (!report) {
        riskScoreEl.textContent = "--";
        threatTypeEl.textContent = "No data available";
        aiStatusEl.textContent = "AI status: unavailable";
        explanationEl.textContent =
            "Unable to analyze this tab. Open an HTTP/HTTPS page and try again.";
        renderReasons([]);
        return;
    }

    const score = Number(report.risk_score || 0);
    riskScoreEl.textContent = String(score);
    riskScoreEl.style.color = getScoreColor(score);
    threatTypeEl.textContent = report.threat_type || "Unknown";
    const aiUsed = Boolean(report.llm_used);
    aiStatusEl.textContent = aiUsed
        ? "AI status: generated by LLM"
        : `AI status: fallback (${report.llm_error || "unknown"})`;
    aiStatusEl.style.color = aiUsed ? "#34d399" : "#f59e0b";
    const trustedLine = report.is_trusted_domain
        ? "This site matches SentinelX trusted-domain checks."
        : "This site is not in SentinelX trusted-domain list.";
    explanationEl.textContent = `${report.explanation || "No explanation provided."} ${trustedLine}`;
    renderReasons(report.reasons || []);
}

async function analyzeCurrentTab(triggerAnalyze = false) {
    const activeTab = await queryActiveTab();
    if (!activeTab || !activeTab.id || !activeTab.url) {
        renderReport(null);
        renderProtectionEvent(null);
        return;
    }

    const messageType = triggerAnalyze ? "TRIGGER_ANALYZE" : "GET_TAB_REPORT";
    const result = await runtimeMessage({
        type: messageType,
        tabId: activeTab.id,
        url: activeTab.url,
    });

    renderReport(result ? result.report : null);
    renderProtectionEvent(result ? result.lastProtectionEvent : null);

    if (!triggerAnalyze) {
        renderDownloadAlert(result ? result.lastDownloadAlert : null);
    } else {
        chrome.storage.local.get(["lastDownloadAlert"], (items) => {
            renderDownloadAlert(items.lastDownloadAlert || null);
        });
        chrome.storage.local.get(["lastProtectionEvent"], (items) => {
            renderProtectionEvent(items.lastProtectionEvent || null);
        });
    }
}

analyzeBtn.addEventListener("click", () => analyzeCurrentTab(true));
analyzeCurrentTab(false);
